source/src/model/Pessoa.java
package model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Pessoa {
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private long id;
	
	@Column 
	private String nome;
	
	@Column 
	private String email;
	
	@Column 
	private String telefone;
	
	
	

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}
	
}

source/src/controller/PessoaMB.java
package controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;

import dao.PessoaDAO;
import model.Pessoa;

@ManagedBean
public class PessoaMB {
	private Pessoa pessoa;
	private PessoaDAO pessoaDAO;
	private List<Pessoa> Lista;	
	
	public PessoaMB() {
		pessoaDAO = new PessoaDAO();
		pessoa = new Pessoa();
		
		Lista = pessoaDAO.listarTodos();				
	}
	
	public Pessoa getPessoa(){
		return this.pessoa;
	}
	
	public void setPessoa(Pessoa pessoa){
		this.pessoa = pessoa;
	}
	
	public List<Pessoa> getList() {
		return this.Lista;
	}
	
	public void salvar() {
		pessoaDAO.salvar(pessoa);
		pessoa = new Pessoa();
		Lista = pessoaDAO.listarTodos();

		addMessage("Pessoa salva com sucesso!!");
		
	}
	
	public void addMessage(String summary) {
	        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, summary,  null);
	        FacesContext.getCurrentInstance().addMessage(null, message);
	}
}	
    

source/WebContent/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"   
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<f:view contentType="text/html"></f:view>

<h:head>

</h:head>


<h:body>
	<h:form>
	
	<!-- Form de Cadastro -->
		<h:panelGrid id="panelgrid" columns="2" cellpadding="5">
			<p:outputLabel value="Nome:" for="acNome" />
			<p:autoComplete id="acNome" value="#{pessoaMB.pessoa.nome}" />
			<p:outputLabel value="E-Mail:" for="acEmail" />
			<p:autoComplete id="acEmail" value="#{pessoaMB.pessoa.email}" />
			<p:outputLabel value="Telefone:" for="acTelefone" />
			<p:autoComplete id="acTelefone" value="#{pessoaMB.pessoa.telefone}" />
 			<p:growl id="messages" /> 
			<p:splitButton value="salvar" action="#{pessoaMB.salvar}"
				type="button" update="panelgrid" icon="ui-icon-disk">
			</p:splitButton>


			<!-- Grid de Consulta -->
			<p:dataTable var="c" value="#{pessoaMB.list}">
				<p:column headerText="Id">
					<h:outputText value="#{c.id}" />
				</p:column>
				<p:column headerText="Nome">
					<h:outputText value="#{c.nome}" />
				</p:column>
				<p:column headerText="Email">
					<h:outputText value="#{c.email}" />
				</p:column>
				<p:column headerText="Telefone">
					<h:outputText value="#{c.telefone}" />
				</p:column>
			</p:dataTable>
		</h:panelGrid>
	</h:form>
	
</h:body>


</html>